
let products = [
    {id:1, name:"amd560", price:"100", category:"graphics cards", img:["../productsImages/amd560_1.jfif","../productsImages/amd560_2.jfif"], description: "Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:2, name:"amd570", price:"200", category:"graphics cards", img:["../productsImages/amd570_1.jfif","../productsImages/amd570_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:3, name:"amd5500", price:"300", category:"graphics cards", img:["../productsImages/amd5500_1.jfif","../productsImages/amd5500_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:4, name:"amd5700", price:"400", category:"graphics cards", img:["../productsImages/amd5700_1.jfif","../productsImages/amd5700_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:5, name:"amd6600", price:"500", category:"graphics cards", img:["../productsImages/amd6600_1.jfif","../productsImages/amd6600_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:6, name:"amd6800", price:"600", category:"graphics cards", img:["../productsImages/amd6800_1.jfif","../productsImages/amd6800_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:8, name:"nvidia1080", price:"700", category:"graphics cards", img:["../productsImages/nvidia1080_1.jfif","../productsImages/nvidia1080_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:9, name:"nvidia1650", price:"800", category:"graphics cards", img:["../productsImages/nvidia1650_1.jfif","../productsImages/nvidia1650_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:10, name:"nvidia1660", price:"900", category:"graphics cards", img:["../productsImages/nvidia1660_1.jfif","../productsImages/nvidia1660_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:11, name:"nvidia2070", price:"1000", category:"graphics cards", img:["../productsImages/nvidia2070_1.jfif","../productsImages/nvidia2070_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:12, name:"nvidia2080", price:"1100", category:"graphics cards", img:["../productsImages/nvidia2080_1.jfif","../productsImages/nvidia2080_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:13, name:"nvidia3060", price:"1200", category:"graphics cards", img:["../productsImages/nvidia3060_1.jfif","../productsImages/nvidia3060_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:14, name:"nvidia3070", price:"1300", category:"graphics cards", img:["../productsImages/nvidia3070_1.jfif","../productsImages/nvidia3070_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:15, name:"nvidia3080", price:"1400", category:"graphics cards", img:["../productsImages/nvidia3080_1.jfif","../productsImages/nvidia3080_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:16, name:"nvidia3090", price:"1500", category:"graphics cards", img:["../productsImages/nvidia3090_1.jfif","../productsImages/nvidia3090_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:17, name:"nvidiaTitan", price:"1600", category:"graphics cards", img:["../productsImages/nvidiaTitan_1.jfif","../productsImages/nvidiaTitan_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},


    

    {id:18, name:"intel i3 3210", price:"100", category:"processors", img:["../productsImages/intel_i3_3210_1.jfif","../productsImages/intel_i3_3210_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:19, name:"intel i3 3220", price:"200", category:"processors", img:["../productsImages/intel_i3_3220_1.jfif","../productsImages/intel_i3_3220_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:20, name:"intel i3 7100", price:"300", category:"processors", img:["../productsImages/intel_i3_7100_1.jfif","../productsImages/intel_i3_7100_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:21, name:"intel9100", price:"400", category:"processors", img:["../productsImages/intel_i3_9100_1.jfif","../productsImages/intel_i3_9100_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:21, name:"intel10105", price:"500", category:"processors", img:["../productsImages/intel_i3_10105_1.jfif","../productsImages/intel_i3_10105_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:21, name:"intel10300", price:"600", category:"processors", img:["../productsImages/intel_i3_10300_1.jfif","../productsImages/intel_i3_10300_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:22, name:"intel7400", price:"700", category:"processors", img:["../productsImages/intel_i5_7400_1.jfif","../productsImages/intel_i5_7400_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:23, name:"intel i5 8600", price:"800", category:"processors", img:["../productsImages/intel_i5_8600_1.jfif","../productsImages/intel_i5_8600_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:24, name:"intel9600", price:"900", category:"processors", img:["../productsImages/intel_i5_9600_1.jfif","../productsImages/intel_i5_9600_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:25, name:"intel10600", price:"1000", category:"processors", img:["../productsImages/intel_i5_10600_1.jfif","../productsImages/intel_i5_10600_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:26, name:"intel11500", price:"1100", category:"processors", img:["../productsImages/intel_i5_11500_1.jfif","../productsImages/intel_i5_11500_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:27, name:"intel8700", price:"1200", category:"processors", img:["../productsImages/intel_i7_8700_1.jfif","../productsImages/intel_i7_8700_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:28, name:"intel8900", price:"1300", category:"processors", img:["../productsImages/intel_i7_8900_1.jfif","../productsImages/intel_i7_8900_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:29, name:"intel9900", price:"1400", category:"processors", img:["../productsImages/intel_i7_9900_1.jfif","../productsImages/intel_i7_9900_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:30, name:"nvidiaTitan", price:"1500", category:"processors", img:["../productsImages/intel_i3_3210_1.jfif","../productsImages/intel_i3_3210_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:31, name:"intel11700", price:"1600", category:"processors", img:["../productsImages/intel_i7_11700_1.jfif","../productsImages/intel_i7_11700_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},




    {id:32, name:"intel_nvme1tb", price:"100", category:"storage drive", img:["../productsImages/storage_intel_nvme1tb_1.jpg","../productsImages/storage_intel_nvme1tb_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:33, name:"intel_nvme2tb", price:"200", category:"storage drive", img:["../productsImages/storage_intel_nvme2tb_1.jpg","../productsImages/storage_intel_nvme2tb_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:34, name:"intel_nvme250g", price:"300", category:"storage drive", img:["../productsImages/storage_intel_nvme250g_1.jpg","../productsImages/storage_intel_nvme250g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:35, name:"intel_nvme500g", price:"400", category:"storage drive", img:["../productsImages/storage_intel_nvme500g_1.jfif","../productsImages/storage_intel_nvme500g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:36, name:"kingston_ssd120g", price:"500", category:"storage drive", img:["../productsImages/storage_kingston_ssd120g_1.jfif","../productsImages/storage_kingston_ssd120g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:37, name:"kingston_ssd480g", price:"600", category:"storage drive", img:["../productsImages/storage_kingston_ssd480g_1.jpg","../productsImages/storage_kingston_ssd480g_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:38, name:"samsung_nvme2tb", price:"700", category:"storage drive", img:["../productsImages/storage_samsung_nvme2tb_1.jpg","../productsImages/storage_samsung_nvme2tb_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:39, name:"samsung_nvme500g", price:"800", category:"storage drive", img:["../productsImages/storage_samsung_nvme500g_1.jpg","../productsImages/storage_samsung_nvme500g_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:40, name:"samsung_ssd1tb", price:"900", category:"storage drive", img:["../productsImages/storage_samsung_ssd1tb_1.jpg","../productsImages/storage_samsung_ssd1tb_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:41, name:"samsung_ssd250g", price:"1000", category:"storage drive", img:["../productsImages/storage_samsung_ssd250g_1.jpg","../productsImages/storage_samsung_ssd250g_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:42, name:"samsung_ssd500g", price:"1100", category:"storage drive", img:["../productsImages/storage_samsung_ssd500g_1.jpg","../productsImages/storage_samsung_ssd500g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:43, name:"seagate_hdd500g", price:"1200", category:"storage drive", img:["../productsImages/storage_seagate_500g_1.jfif","../productsImages/storage_seagate_500g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:44, name:"seagate_hdd2t", price:"1300", category:"storage drive", img:["../productsImages/storage_seagate_hdd2t_1.jpg","../productsImages/storage_seagate_hdd2t_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:45, name:"ssd480g", price:"1400", category:"storage drive", img:["../productsImages/storage_ssd2tb_1.jfif","../productsImages/storage_ssd2tb_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:46, name:"ssd480g", price:"1500", category:"storage drive", img:["../productsImages/storage_ssd480g_1.jpg","../productsImages/storage_ssd480g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:47, name:"wd_hdd1t", price:"1600", category:"storage drive", img:["../productsImages/storage_wd_hdd1t_1.jfif","../productsImages/storage_wd_hdd1t_2.jpg"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:48, name:"wd_hdd2t", price:"1700", category:"storage drive", img:["../productsImages/storage_wd_hdd2t_1.jpg","../productsImages/storage_wd_hdd2t_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:49, name:"wd_nvme500g", price:"1800", category:"storage drive", img:["../productsImages/storage_wd_nvme500g_1.jpg","../productsImages/storage_wd_nvme500g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},




    {id:50, name:"adata16g", price:"100", category:"ram memories", img:["../productsImages/memory_adata16g_1.jpg", "../productsImages/memory_adata16g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:51, name:"adata16x2g", price:"200", category:"ram memories", img:["../productsImages/memory_adata16x2g_1.jfif", "../productsImages/memory_adata16x2g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:52, name:"adata32g", price:"300", category:"ram memories", img:["../productsImages/memory_adata32g_1.jpg", "../productsImages/memory_adata32g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:53, name:"adata8g", price:"400", category:"ram memories", img:["../productsImages/memory_adata8g_1.jpg", "../productsImages/memory_adata8g_1.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:54, name:"adata8x2g", price:"500", category:"ram memories", img:["../productsImages/memory_adata8x2g_1.jfif", "../productsImages/memory_adata8x2g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:55, name:"corsair16g", price:"600", category:"ram memories", img:["../productsImages/memory_corsair16g_1.jpg", "../productsImages/memory_corsair16g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:56, name:"corsair16x2g", price:"700", category:"ram memories", img:["../productsImages/memory_corsair16x2g_1.jpg", "../productsImages/memory_corsair16x2g_2.jpg.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:57, name:"corsair32g", price:"800", category:"ram memories", img:["../productsImages/memory_corsair32g_1.jfif", "../productsImages/memory_corsair32g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:58, name:"corsair4g", price:"900", category:"ram memories", img:["../productsImages/memory_corsair4g_1.jpg", "../productsImages/memory_corsair4g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:59, name:"corsair4x2g", price:"1000", category:"ram memories", img:["../productsImages/memory_corsair4x2g_1.jpg", "../productsImages/memory_corsair4x2g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:60, name:"corsair8g", price:"1100", category:"ram memories", img:["../productsImages/memory_corsair8g_1.jfif", "../productsImages/memory_corsair8g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:61, name:"corsair8x2g", price:"1200", category:"ram memories", img:["../productsImages/memory_corsair8x2g_1.jpg", "../productsImages/memory_corsair8x2g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:62, name:"crucial16g", price:"1300", category:"ram memories", img:["../productsImages/memory_crucial16g_1.jfif", "../productsImages/memory_crucial16g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:63, name:"crucial32g", price:"1400", category:"ram memories", img:["../productsImages/memory_crucial32g_1.jfif", "../productsImages/memory_crucial32g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:64, name:"crucial4g", price:"1500", category:"ram memories", img:["../productsImages/memory_crucial4g_1.jpg", "../productsImages/memory_crucial4g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},
    {id:65, name:"crucial8g", price:"1600", category:"ram memories", img:["../productsImages/memory_crucial8g_1.jpg", "../productsImages/memory_crucial8g_2.jfif"], description:"Lorem ipsum dolor sit.Pariatur eaque expedita dicta!Delectus omnis dolorum neque!Sed aperiam quos quo!"},

]

